SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 're_properties' 
AND TABLE_SCHEMA = DATABASE()
AND COLUMN_NAME LIKE 'pg_%' OR COLUMN_NAME LIKE '%virtual%'
ORDER BY ORDINAL_POSITION;
